FROM centos:latest

USER root

WORKDIR /td-1.8.0

RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    cd /td-1.8.0 && \
    yum update -y && \
    dnf --enablerepo=powertools -y install gperf && \
    yum -y install gcc-c++ make git zlib-devel openssl-devel php cmake java-11-openjdk-devel